name: Composite Action - Cloud Config
description: Get the Cloud Config

inputs:
  CLOUD_PROVIDER:
    required: true
    type: string
  DEPLOY_ENV:
    required: true
    type: string
  SVC_NAME:
    required: true
    type: string
  DEVOPS_REPO:
    required: false
    type: string
    default: "javelin-cloud"
outputs:
  deploy_cloud:
    value: ${{ steps.cloud.outputs.deploy_cloud }}
  deploy_region:
    value: ${{ steps.cloud.outputs.deploy_region }}

runs:
  using: "composite"
  steps:
    - name: Cloud Config
      id: cloud
      shell: bash
      run: |-
        if [[ -f ${{ env.DEVOPS_REPO }}/app-config/${{ inputs.SVC_NAME }}/common-config.json ]] ; then
          export json_file="${{ env.DEVOPS_REPO }}/app-config/${{ inputs.SVC_NAME }}/common-config.json"
        else
          export json_file="${{ env.DEVOPS_REPO }}/app-config/javelin-default/common-config.json"
        fi

        if [[ ${{ inputs.CLOUD_PROVIDER }} == "find" ]] ; then
          if jq -e '.cloud.aws.${{ inputs.DEPLOY_ENV }}' ${json_file} > /dev/null; then
            echo "deploy_cloud=aws" >> ${GITHUB_OUTPUT}
          elif jq -e '.cloud.gcp.${{ inputs.DEPLOY_ENV }}' ${json_file} > /dev/null; then
            echo "deploy_cloud=gcp" >> ${GITHUB_OUTPUT}
          else
            echo "deploy_cloud=nil" >> ${GITHUB_OUTPUT}
          fi
        else
          deploy_region=$(cat ${json_file} | jq -r '.cloud.${{ inputs.CLOUD_PROVIDER }}.${{ inputs.DEPLOY_ENV }}.region')
          echo "deploy_region=${deploy_region}" >> ${GITHUB_OUTPUT}
        fi