name: Composite Action - Cloud Config
description: Get the Cloud Config

inputs:
  CLOUD_PROVIDER:
    required: true
    type: string
  DEPLOY_ENV:
    required: true
    type: string
  DEVOPS_REPO:
    required: false
    type: string
    default: "javelin-cloud"
outputs:
  deploy_region:
    value: ${{ steps.cloud.outputs.deploy_region }}

runs:
  using: "composite"
  steps:
    - name: Cloud Config
      id: cloud
      shell: bash
      run: |-
        deploy_region=$(cat ${{ env.DEVOPS_REPO }}/app-config/javelin-default/cloud-config.json | jq -r '.${{ input.CLOUD_PROVIDER }}.${{ input.DEPLOY_ENV }}.region')
        echo "deploy_region=${deploy_region}" >> ${GITHUB_OUTPUT}