name: Composite Action - DevOps CICD Slack Payload
description: Templating the DevOps CICD Slack Payload

inputs:
  SHORT_SHA:
    required: true
    type: string
  SVC_NAME:
    required: true
    type: string
  DOCKER_IMAGE:
    required: true
    type: string
  JOB_STATUS:
    required: true
    type: string
  SLACK_CHANNEL_ID:
    required: true
    type: string
  SLACK_PAYLOAD_JSON:
    required: true
    type: string
  JOB_STATUS_SUCCESS_MARK:
    required: false
    type: string
    default: ":white_check_mark:"
  JOB_STATUS_FAIL_MARK:
    required: false
    type: string
    default: ":x:"
  DEVOPS_REPO:
    required: false
    type: string
    default: "javelin-cloud"
  PIPELINE_DEBUG:
    required: false
    type: string
    default: "disable"

runs:
  using: "composite"
  steps:
    - name: CICD Slack Payload
      env:
        SVC_NAME: "${{ inputs.SVC_NAME }}"
        DOCKER_IMAGE: "${{ inputs.DOCKER_IMAGE }}"
        JOB_STATUS: "${{ inputs.JOB_STATUS }}"
        SLACK_CHANNEL_ID: ${{ inputs.SLACK_CHANNEL_ID }}
        COMMIT_AUTHOR: ${{ github.event.commits[0].author.name }}
        COMMIT_SHA: ${{ inputs.SHORT_SHA }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      shell: bash
      run: |-
        if [[ ${{ env.JOB_STATUS }} == "success" ]] ; then
          export JOB_STATUS_MARK=${{ inputs.JOB_STATUS_SUCCESS_MARK }}
        else
          export JOB_STATUS_MARK=${{ inputs.JOB_STATUS_FAIL_MARK }}
        fi
        envsubst < ${{ inputs.DEVOPS_REPO }}/slack-notify/${{ inputs.SLACK_PAYLOAD_JSON }} > ${{ inputs.SLACK_PAYLOAD_JSON }}
        if [[ "${{ inputs.PIPELINE_DEBUG }}" == "enable" ]] ; then
          cat ${{ inputs.SLACK_PAYLOAD_JSON }}
        fi