name: Composite Action - Environment Auth Details
description: Authentication Details for the Deploy Environment

inputs:
  DEPLOY_ENV:
    required: true
    type: string
outputs:
  deploy_env:
    value: ${{ steps.auth.outputs.deploy_env }}
  cicd_sa:
    value: ${{ steps.auth.outputs.cicd_sa }}
  sql_secret:
    value: ${{ steps.auth.outputs.sql_secret }}
  cicd_role:
    value: ${{ steps.auth.outputs.cicd_role }}
  rds_secret:
    value: ${{ steps.auth.outputs.rds_secret }}
  cicd_secret:
    value: ${{ steps.auth.outputs.cicd_secret }}
  cicd_secret_manual:
    value: ${{ steps.auth.outputs.cicd_secret_manual }}
  wip_provider:
    value: ${{ steps.auth.outputs.wip_provider }}

runs:
  using: "composite"
  steps:
    - name: Setting up Deploy Env
      id: auth
      shell: bash
      run: |-
        case "${{ inputs.DEPLOY_ENV }}" in
          "dev1")
              echo "deploy_env=${{ inputs.DEPLOY_ENV }}" >> ${GITHUB_OUTPUT}
              echo "cicd_role=javelin-${{ inputs.DEPLOY_ENV }}-cicd-github-action" >> ${GITHUB_OUTPUT}
              echo "rds_secret=javelin-${{ inputs.DEPLOY_ENV }}-aurora-postgres" >> ${GITHUB_OUTPUT}
              echo "cicd_secret=javelin-${{ inputs.DEPLOY_ENV }}-cicd" >> ${GITHUB_OUTPUT}
              echo "cicd_secret_manual=javelin-${{ inputs.DEPLOY_ENV }}-cicd-manual" >> ${GITHUB_OUTPUT}
            ;;
          "dev2")
              echo "deploy_env=${{ inputs.DEPLOY_ENV }}" >> ${GITHUB_OUTPUT}
              echo "cicd_role=javelin-${{ inputs.DEPLOY_ENV }}-cicd-github-action" >> ${GITHUB_OUTPUT}
              echo "rds_secret=javelin-${{ inputs.DEPLOY_ENV }}-aurora-postgres" >> ${GITHUB_OUTPUT}
              echo "cicd_secret=javelin-${{ inputs.DEPLOY_ENV }}-cicd" >> ${GITHUB_OUTPUT}
              echo "cicd_secret_manual=javelin-${{ inputs.DEPLOY_ENV }}-cicd-manual" >> ${GITHUB_OUTPUT}
            ;;
          "demo")
              echo "deploy_env=${{ inputs.DEPLOY_ENV }}" >> ${GITHUB_OUTPUT}
              echo "cicd_sa=javelin-${{ inputs.DEPLOY_ENV }}-cicd-gh-sa@javelin-stage.iam.gserviceaccount.com" >> ${GITHUB_OUTPUT}
              echo "sql_secret=javelin-${{ inputs.DEPLOY_ENV }}-postgres" >> ${GITHUB_OUTPUT}
              echo "cicd_secret=javelin-${{ inputs.DEPLOY_ENV }}-cicd" >> ${GITHUB_OUTPUT}
              echo "cicd_secret_manual=javelin-${{ inputs.DEPLOY_ENV }}-cicd-manual" >> ${GITHUB_OUTPUT}
              echo "wip_provider=${{ vars.GCP_WIP_PROVIDER }}" >> ${GITHUB_OUTPUT}
            ;;
          "stage")
              echo "deploy_env=${{ inputs.DEPLOY_ENV }}" >> ${GITHUB_OUTPUT}
              echo "cicd_sa=javelin-${{ inputs.DEPLOY_ENV }}-cicd-gh-sa@javelin-stage.iam.gserviceaccount.com" >> ${GITHUB_OUTPUT}
              echo "sql_secret=javelin-${{ inputs.DEPLOY_ENV }}-postgres" >> ${GITHUB_OUTPUT}
              echo "cicd_secret=javelin-${{ inputs.DEPLOY_ENV }}-cicd" >> ${GITHUB_OUTPUT}
              echo "cicd_secret_manual=javelin-${{ inputs.DEPLOY_ENV }}-cicd-manual" >> ${GITHUB_OUTPUT}
              echo "wip_provider=${{ vars.GCP_WIP_PROVIDER }}" >> ${GITHUB_OUTPUT}
            ;;
          "saas")
              echo "deploy_env=${{ inputs.DEPLOY_ENV }}" >> ${GITHUB_OUTPUT}
              echo "cicd_sa=javelin-${{ inputs.DEPLOY_ENV }}-cicd-gh-sa@javelin-saas.iam.gserviceaccount.com" >> ${GITHUB_OUTPUT}
              echo "sql_secret=javelin-${{ inputs.DEPLOY_ENV }}-postgres" >> ${GITHUB_OUTPUT}
              echo "cicd_secret=javelin-${{ inputs.DEPLOY_ENV }}-cicd" >> ${GITHUB_OUTPUT}
              echo "cicd_secret_manual=javelin-${{ inputs.DEPLOY_ENV }}-cicd-manual" >> ${GITHUB_OUTPUT}
              echo "wip_provider=${{ vars.GCP_SAAS_WIP_PROVIDER }}" >> ${GITHUB_OUTPUT}
            ;;
          *)
              echo "Failed to find the Authentication details for ${{ inputs.DEPLOY_ENV }}"
            ;;
        esac
